# Global settings:
http 80;
rtmp 1935;
pulsedb /var/lib/flussonic;
session_log /var/lib/flussonic;
edit_auth flussonic letmein!;

# DVRs:

# Remote sources:

# Ingest streams:

# Dynamic rewrites:

# Publish locations:

# Disk file caches:

# VOD locations:

# DVB cards:

# Plugins:


